descriptions = (
    "Avocado Toastery",
    "Dogecoin Exchange",
    "Invisible Art Gallery",
    "Garden Gnomes R Us",
    "Flat Earth Society Membership Dues",
    "Pet Rock Emporium",
    "Bigfoot Trackers Club Fee",
    "Caged Civet Coffee Cafe",
    "Telepathy Training Center",
    "Platinum Pet Food Inc",
    "Decadent Delights",
    "Illuminati Membership Dues",
    "Artisanal Water Bar",
    "Atlantis Scuba Tours",
    "Star Naming Rights Broker",
    "Vogon Poetry Bookstore",
    "Bigfoot Trail Guides",
    "Time Travel Experience Package",
    "Mars Real Estate Agency",
    "Alien Abduction Insurance Premium",
)

passwords = (
    "123456",
    "123456789",
    "12345",
    "qwerty",
    "password",
    "12345678",
    "111111",
    "123123",
    "1234567890",
    "1234567",
    "qwerty123",
    "000000",
    "1q2w3e",
    "aa12345678",
    "abc123",
    "password1",
    "1234",
    "qwertyuiop",
    "123321",
    "password123",
    "hunter2",
)
