# Generated by Django 4.1.7 on 2023-07-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaky_ledger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date_of_transaction",
            field=models.DateTimeField(),
        ),
    ]
